package sigma.stark

import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers
import scala.io.Source

/** Known-Answer-Test parity for the EIP-0045 verifyStark FRI verifier
  * ([[FriVerifier]]).
  *
  * Expected values come from EXTERNAL oracles — never from the Scala code
  * under test (oracle-parity rule):
  *
  *  - `stark-kats/fri_kat.tsv` (generated by `stark-kat/src/bin/fri_kat.rs`):
  *    synthetic FRI proofs over 0/1/2/3 fold rounds, produced by risc0-zkp
  *    1.2.6's own `prove::fri::fri_prove` (byte-asserted) with per-round
  *    `(pos, goal)` checkpoints from the prover's own evaluation buffers;
  *    every vector — positive AND negative — was replayed through
  *    risc0-zkp's own `Verifier::fri_verify` before emission.
  */
class FriKatSpec extends AnyFunSuite with Matchers {

  // --------------------------------------------------------------------
  // Helpers
  // --------------------------------------------------------------------

  private def lines(resource: String): Seq[String] = {
    val is = getClass.getResourceAsStream(resource)
    require(is != null, s"missing KAT resource $resource — run stark-kat fri_kat generator")
    try Source.fromInputStream(is, "UTF-8").getLines().filterNot(_.startsWith("#")).toList
    finally is.close()
  }

  /** Wire words are u32; parse via Long so values >= 2^31 round-trip into
    * bit-identical Ints.
    */
  private def words(s: String): Array[Int] =
    if (s.isEmpty) Array.empty[Int] else s.split(',').map(w => java.lang.Long.parseLong(w.trim).toInt)

  // --------------------------------------------------------------------
  // fri_kat.tsv parsing
  // --------------------------------------------------------------------

  private case class FriCaseVec(
      name: String,
      degree: Int,
      queries: Int,
      initialCommit: Array[Int],
      finalOff: Int,
      proof: Array[Int],
      /** qck(q)(r) = (pos, goal) before round r; last entry = final-poly
        * comparison state.
        */
      qck: Vector[Vector[(Int, Ext4)]],
      badWords: Seq[(Int, Int)],
      truncates: Seq[Int],
      badGoals: Seq[Int])

  private case class FriKat(rouFwd: Array[Int], rouRev: Array[Int], cases: Seq[FriCaseVec])

  private lazy val kat: FriKat = {
    var rouFwd: Array[Int] = null
    var rouRev: Array[Int] = null
    var cases = Vector.empty[FriCaseVec]
    var cur: FriCaseVec = null
    var qck = Map.empty[(Int, Int), (Int, Ext4)]
    lines("/stark-kats/fri_kat.tsv").foreach { line =>
      if (line.startsWith("rou_fwd:")) rouFwd = words(line.stripPrefix("rou_fwd:"))
      else if (line.startsWith("rou_rev:")) rouRev = words(line.stripPrefix("rou_rev:"))
      else if (line.startsWith("case:")) {
        val p = line.stripPrefix("case:").split(',')
        cur = FriCaseVec(p(0), p(1).toInt, p(2).toInt, null, -1, null, Vector.empty,
          Vector.empty, Vector.empty, Vector.empty)
        qck = Map.empty
      } else if (line.startsWith("initial_commit:")) {
        cur = cur.copy(initialCommit = words(line.stripPrefix("initial_commit:")))
      } else if (line.startsWith("final_off:")) {
        cur = cur.copy(finalOff = line.stripPrefix("final_off:").toInt)
      } else if (line.startsWith("proof:")) {
        cur = cur.copy(proof = words(line.stripPrefix("proof:")))
      } else if (line.startsWith("qck:")) {
        val Array(qr, v) = line.stripPrefix("qck:").split(" -> ")
        val Array(q, r) = qr.split(',').map(_.trim.toInt)
        val vs = words(v)
        qck += ((q, r) -> ((vs(0), Ext4(vs(1), vs(2), vs(3), vs(4)))))
      } else if (line.startsWith("badword:")) {
        val p = line.stripPrefix("badword:").split(',')
        cur = cur.copy(badWords = cur.badWords :+ ((p(0).toInt, java.lang.Long.parseLong(p(1)).toInt)))
      } else if (line.startsWith("truncate:")) {
        cur = cur.copy(truncates = cur.truncates :+ line.stripPrefix("truncate:").toInt)
      } else if (line.startsWith("badgoal:")) {
        cur = cur.copy(badGoals = cur.badGoals :+ line.stripPrefix("badgoal:").toInt)
      } else if (line == "endcase") {
        val rPerQ = qck.keys.groupBy(_._1).map { case (q, ks) => q -> ks.map(_._2).max }
        val chains = (0 until cur.queries).toVector.map { q =>
          (0 to rPerQ(q)).toVector.map(r => qck((q, r)))
        }
        cases = cases :+ cur.copy(qck = chains)
        cur = null
      } else fail(s"unknown fri KAT line: ${line.take(60)}")
    }
    require(rouFwd != null && rouRev != null && cases.nonEmpty, "incomplete fri_kat.tsv")
    FriKat(rouFwd, rouRev, cases)
  }

  /** Mirror of the generator's `oracle_fri_ok` (same accept criterion, so
    * a Scala reject here corresponds 1:1 to an oracle-confirmed reject).
    * Inner convention shared with the generator: known position -> its
    * recorded round-0 goal, unknown position -> 0; `badGoal` makes the
    * q-th inner call return goal + 1.
    */
  private def replayOk(v: FriCaseVec, proof: Array[Int], badGoal: Option[Int]): Boolean = {
    val goalMap: Map[Int, Ext4] = v.qck.map(c => c.head._1 -> c.head._2).toMap
    val iop = new ReadIop(proof)
    iop.commit(v.initialCommit)
    var call = 0
    val inner: Int => Either[String, Ext4] = { pos =>
      var g = goalMap.getOrElse(pos, Ext4.Zero)
      if (badGoal.contains(call)) g = g + Ext4.One
      call += 1
      Right(g)
    }
    FriVerifier.friVerify(iop, v.degree, v.queries, inner) match {
      case Left(_) => false
      case Right(_) => iop.verifyComplete
    }
  }

  // --------------------------------------------------------------------
  // Constants parity
  // --------------------------------------------------------------------

  test("FRI roots-of-unity tables match risc0-core's own constants") {
    kat.rouFwd should have length 28
    kat.rouRev should have length 28
    FriVerifier.rouFwdSnapshot shouldBe kat.rouFwd
    FriVerifier.rouRevSnapshot shouldBe kat.rouRev
    // Spot-check the algebra the tables promise: RouFwd(k) has order 2^k
    // and RouRev(k) is its inverse.
    (0 to 27).foreach { k =>
      BabyBear.pow(FriVerifier.RouFwd(k), 1L << k) shouldBe 1
      BabyBear.mul(FriVerifier.RouFwd(k), FriVerifier.RouRev(k)) shouldBe 1
    }
  }

  test("FRI roots expose only defensive snapshots") {
    val forward = FriVerifier.rouFwdSnapshot
    val reverse = FriVerifier.rouRevSnapshot
    forward(1) ^= 1
    reverse(1) ^= 1

    FriVerifier.rouFwdSnapshot shouldBe kat.rouFwd
    FriVerifier.rouRevSnapshot shouldBe kat.rouRev
    BabyBear.mul(FriVerifier.RouFwd(1), FriVerifier.RouRev(1)) shouldBe 1
  }

  test("FRI profile constants match the pinned stock-profile oracle") {
    val params = lines("/stark-kats/eip0045-direct/profile-oracle.tsv")
      .filter(_.startsWith("param\t"))
      .map(_.split('\t'))
      .map(p => p(1) -> p(2))
      .toMap
    FriVerifier.Queries shouldBe params("queries").toInt
    FriVerifier.InvRate shouldBe params("inv_rate").toInt
    FriVerifier.FriFold shouldBe params("fri_fold").toInt
    FriVerifier.FriFoldPo2 shouldBe params("fri_fold_po2").toInt
    FriVerifier.FriMinDegree shouldBe params("fri_min_degree").toInt
  }

  // --------------------------------------------------------------------
  // Synthetic prover-built proofs (accept + per-round checkpoints)
  // --------------------------------------------------------------------

  test("FriVerifier replays prover-built FRI proofs across 0/1/2/3 fold rounds") {
    kat.cases.map(_.name) shouldBe
      Seq("deg256_r0", "deg4096_r1", "deg65536_r2", "deg262144_r3")
    kat.cases.foreach { v =>
      withClue(s"case ${v.name}: ") {
        // Round structure implied by the checkpoints must match the
        // protocol's fold recursion (degree/16 while degree > 256).
        var expRounds = 0
        var d = v.degree
        while (d > FriVerifier.FriMinDegree) { expRounds += 1; d /= FriVerifier.FriFold }
        v.qck.foreach(_.length shouldBe (expRounds + 1))

        val goalMap: Map[Int, Ext4] = v.qck.map(c => c.head._1 -> c.head._2).toMap
        val iop = new ReadIop(v.proof)
        iop.commit(v.initialCommit)
        var call = 0
        val inner: Int => Either[String, Ext4] = { pos =>
          withClue(s"query $call drawn position: ") { pos shouldBe v.qck(call)(0)._1 }
          call += 1
          Right(goalMap(pos))
        }
        val probe: FriVerifier.Probe = { (q, r, pos, goal) =>
          withClue(s"checkpoint q$q r$r: ") {
            val (expPos, expGoal) = v.qck(q)(r)
            pos shouldBe expPos
            goal shouldBe expGoal
          }
        }
        FriVerifier.friVerify(iop, v.degree, v.queries, inner, probe) shouldBe Right(())
        call shouldBe v.queries
        iop.verifyComplete shouldBe true
      }
    }
  }

  // --------------------------------------------------------------------
  // Oracle-confirmed rejects
  // --------------------------------------------------------------------

  test("FriVerifier rejects corrupted proof words (oracle-confirmed rejects)") {
    kat.cases.flatMap(_.badWords) should not be empty
    kat.cases.foreach { v =>
      v.badWords.foreach { case (pos, xor) =>
        val corrupted = v.proof.clone()
        corrupted(pos) ^= xor
        withClue(s"case ${v.name} badword $pos^$xor: ") {
          replayOk(v, corrupted, None) shouldBe false
        }
      }
    }
  }

  test("FriVerifier rejects truncated proofs (oracle-confirmed rejects)") {
    kat.cases.foreach { v =>
      v.truncates.foreach { keep =>
        withClue(s"case ${v.name} truncate $keep: ") {
          replayOk(v, v.proof.take(keep), None) shouldBe false
        }
      }
    }
  }

  test("FriVerifier rejects a wrong DEEP-ALI goal (oracle-confirmed rejects)") {
    kat.cases.flatMap(_.badGoals) should not be empty
    kat.cases.foreach { v =>
      v.badGoals.foreach { q =>
        withClue(s"case ${v.name} badgoal $q: ") {
          replayOk(v, v.proof, Some(q)) shouldBe false
        }
      }
    }
  }

  test("FriVerifier surfaces inner failures without reading further") {
    val v = kat.cases.head
    val iop = new ReadIop(v.proof)
    iop.commit(v.initialCommit)
    val res = FriVerifier.friVerify(iop, v.degree, v.queries, _ => Left("no goal"))
    res.isLeft shouldBe true
    res.left.get should include("no goal")
  }

  test("FriVerifier rejects an empty stream instead of throwing") {
    val iop = new ReadIop(Array.empty[Int])
    FriVerifier.friVerify(iop, 4096, 50, _ => Right(Ext4.Zero)).isLeft shouldBe true
  }

}
