package sigmastate.utils

import sigma.ast.SMethod
import sigma.util.PrintExtensions._
import scala.util.Try
import Helpers._ // required for Scala 2.11

/** Generate as a console output all InfoObject objects.
  * Those provide stable identifiers to access metadata information.
  * This should be regenerated each time metadata is changed.
  * Example:
  * object AppendInfo extends InfoObject {
  *   private val method = SMethod.fromIds(12, 9)
  *   val thisArg = method.argInfo("this")
  *   val otherArg = method.argInfo("other")
  *   ...
  * }
  * The following consistency checks are performed:
  * 1) every func/method argument has attached ArgInfo
  * 2) method is resolvable by ids (e.g. as SMethod.fromIds(12, 9))
  * 3) func is resolvable by name (e.g. predefinedOps.funcs("sigmaProp"))
  */
object GenInfoObjects extends SpecGen {

  /** Generates the bodies of all `InfoObject` definitions, alphabetically sorted by
    * operation name, performing the consistency checks documented above. */
  def generateOperationsBodies(): String = {
    val table = collectOpsTable()
    val infos = table.map { case (d, m, f) =>
      // When an opCode is shared by a predefined func and a (V6) method (e.g. Xor's
      // `binary_|` and `SGlobal` xor, or `getVar` and `Context.getVar`), document the func.
      // The method form carries a `this` receiver that is NOT a serialized operand of the
      // node, so using it would inject a spurious argument and mis-describe the node's args,
      // which serializers read via `opDesc.argInfos(i)`.
      val methodForDoc = if (f.isDefined) None else m
      getOpInfo(d, methodForDoc, f)
    }

    val infoStrings = infos.sortBy(_.opDesc.typeName).map { info =>
      val opName = info.opDesc.typeName

      val res = info.op match {
        case Right(m) =>
          val typeId = m.objType.typeId
          assert(m.stype.tDom.length == info.args.length,
            s"Method $m has ${m.stype.tDom} arguments, but ${info.args} descriptions attached.")
          Try{SMethod.fromIds(typeId, m.methodId)}
            .fold(t => throw new RuntimeException(s"Cannot resolve method $m using SMethod.fromIds(${typeId}, ${m.methodId})"), _ => ())
          val args = info.args.map { a =>
            s"""val ${a.name}Arg: ArgInfo = method.argInfo("${a.name}")"""
          }
          s"""
            |  object ${opName}Info extends InfoObject {
            |    private val method = SMethod.fromIds(${typeId}, ${m.methodId})
            |    ${args.rep(sep = "\n    ")}
            |    val argInfos: Seq[ArgInfo] = Array(${info.args.rep(a => s"${a.name}Arg")})
            |  }
           """.stripMargin
        case Left(f) =>
          assert(f.declaration.args.length == info.args.length,
            s"Predefined function $f has ${f.declaration.args} arguments, but ${info.args} descriptions attached.")
          val isSpecialFunc = predefFuncRegistry.specialFuncs.get(f.name).isDefined
          Try{assert(predefFuncRegistry.funcs.get(f.name).isDefined || isSpecialFunc)}
              .fold(t => throw new RuntimeException(s"Cannot resolve func $f using predefFuncRegistry.funcs(${f.name})", t), _ => ())
          val args = info.args.map { a =>
            s"""val ${a.name}Arg: ArgInfo = func.argInfo("${a.name}")"""
          }
          s"""
            |  object ${opName}Info extends InfoObject {
            |    private val func = predefinedOps.${ if (isSpecialFunc) "specialFuncs" else "funcs" }("${f.name}")
            |    ${args.rep(sep = "\n    ")}
            |    val argInfos: Seq[ArgInfo] = Array(${info.args.rep(a => s"${a.name}Arg")})
            |  }
           """.stripMargin
      }
      res
    }
    infoStrings.rep(sep = "")
  }

  /** Generates the full content of the `Operations.scala` source file: the package
    * header, the `Operations` object wrapper and all generated `InfoObject` bodies.
    * This is the single source of truth for `sigma.ast.Operations`. */
  def generateOperationsFile(): String = {
    // Only the header uses stripMargin; the bodies are concatenated as-is because they
    // may contain a literal '|' (e.g. the `binary_|` function name in XorInfo).
    val header =
      """package sigma.ast
        |
        |import sigma.serialization.CoreByteWriter.ArgInfo
        |import SigmaPredef.PredefinedFuncRegistry
        |
        |/** WARNING: This file is generated by GenInfoObjects tool.
        |  * Don't edit it directly, use the tool instead to regenerate.
        |  * The operations are alphabetically sorted.
        |  */
        |object Operations {
        |  val predefinedOps = new PredefinedFuncRegistry(StdSigmaBuilder)
        |  trait InfoObject {
        |    def argInfos: Seq[ArgInfo]
        |  }
        |""".stripMargin
    val raw = header + generateOperationsBodies() + "\n}\n"
    // The committed file is kept free of trailing whitespace; mirror that so regeneration
    // is idempotent and produces clean Scala source.
    raw.linesIterator.map(_.replaceAll("[ \t]+$", "")).mkString("\n") + "\n"
  }

  def main(args: Array[String]) = {
    println(generateOperationsFile())
  }

}
